# filename: reservation.feature | Code Generated by Sidekick is for learning and experimentation purposes only.

@reservations
Feature: Reservation management

  Background:
    Given a patron is registered and logged in
    And the catalog contains an available book

  Scenario: A patron can reserve an available book
    When the patron reserves the available book
    Then the reservation response should be 201
    And the reservation status should be "RESERVED"
    And the reservation should contain the book ID
    And the reservation should contain the patron ID
    And the reservation expiration should be 7 days after reservation
    And the response message should be "Book reserved successfully. Please pick up within 7 days."

  Scenario: A patron can view active reservations
    Given the patron has an active reservation
    When the patron requests active reservations
    Then the response status should be 200
    And the active reservations response should contain the reservation
    And the active reservation should include book details
    And the active reservation status should be "RESERVED"

  Scenario: An unauthenticated user cannot create a reservation
    When an unauthenticated user reserves the available book
    Then the response status should be 401
    And the response field "error" should be "UNAUTHORIZED"

  Scenario: A patron cannot reserve an unavailable book
    Given the available book has no available copies
    When the patron reserves the available book
    Then the response status should be 400
    And the response field "error" should be "BOOK_UNAVAILABLE"
    And the response field "availableCopies" should be 0


  Scenario: A librarian can check out a reserved book
    Given the patron has an active reservation
    And a librarian is logged in
    When the librarian checks out the reservation
    Then the response status should be 200
    And the reservation status should be "CHECKED_OUT"
    And the checkout response should contain a checked-out timestamp
    And the due date should be 14 days after checkout
    And the response message should contain "Book checked out successfully"

#  Scenario: A patron cannot check out a reserved book
#    Given the patron has an active reservation
#    When the patron checks out the reservation
#    Then the response status should be 403
#    And the response field "error" should be "FORBIDDEN"

  Scenario: A librarian cannot check out an already checked-out book
    Given the patron has a checked-out reservation
    And a librarian is logged in
    When the librarian checks out the reservation
    Then the response status should be 400
    And the response field "error" should be "INVALID_STATUS"
    And the response field "currentStatus" should be "CHECKED_OUT"

  Scenario: A librarian can return a checked-out book on time
    Given the patron has a checked-out reservation
    And a librarian is logged in
    When the librarian returns the reservation with condition "GOOD"
    Then the response status should be 200
    And the response field "lateDays" should be 0
    And the response field "lateFee" should be 0
    And the response message should be "Book returned successfully"

  Scenario: A patron cannot return a checked-out book
    Given the patron has a checked-out reservation
    When the patron returns the reservation with condition "GOOD"
    Then the response status should be 403
    And the response field "error" should be "FORBIDDEN"

  Scenario: A patron cannot exceed five active reservations
    Given the patron already has 5 active reservations
    When the patron reserves the available book
    Then the response status should be 400
    And the response field "error" should be "RESERVATION_LIMIT_EXCEEDED"
    And the response field "currentReservations" should be 5

  Scenario: A patron can view borrowing history
    When the patron requests borrowing history
    Then the response status should be 200
    And the borrowing history response should be paginated
    And the history should include reservation details
    And the history should include a "wasLate" field

  Scenario: An unauthenticated user cannot view borrowing history
    When an unauthenticated user requests borrowing history
    Then the response status should be 401
    And the response field "error" should be "UNAUTHORIZED"
